INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Beach Cleanup", "Environment", 600, "5/1/20", "6/30/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Food Drive", "Food", 200, "5/1/17", "6/30/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Toys for Children", "Children", 625, "5/1/20", "6/30/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Addiction Counseling", "Recovery", 275, "5/1/20", "6/30/2017");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Breast Cancer Run", "Health", 300, "5/1/20", "6/30/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Counseling Sessions", "Domestic Violence", 265, "5/1/20", "7/31/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Makeup Tutorial", "Youth", 1060, "5/1/20", "5/1/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Kids 5K", "Youth", 200, "5/1/20", "7/31/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Music", "Arts", 115, "5/1/20", "7/31/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Meals on Wheels", "Seniors", 180, "6/1/20", "7/31/20");

INSERT INTO users (name, age) VALUES ("John Marshall", 34);
INSERT INTO users (name, age) VALUES ("Jacob Cub", 29);
INSERT INTO users (name, age) VALUES ("Austin Casey", 24);
INSERT INTO users (name, age) VALUES ("Jordan Marshall", 51);
INSERT INTO users (name, age) VALUES ("Matthew Harris", 50);
INSERT INTO users (name, age) VALUES ("Bill Nye", 55);
INSERT INTO users (name, age) VALUES ("Joseph Stalin", 49);
INSERT INTO users (name, age) VALUES ("Sherry Pie", 45);
INSERT INTO users (name, age) VALUES ("Lena Dunham", 38);
INSERT INTO users (name, age) VALUES ("Shelley Davenport", 84);
INSERT INTO users (name, age) VALUES ("Travis Black", 57);
INSERT INTO users (name, age) VALUES ("Michael Mackie", 33);
INSERT INTO users (name, age) VALUES ("Adam Granduciel", 27);
INSERT INTO users (name, age) VALUES ("Kurt Vile", 26);
INSERT INTO users (name, age) VALUES ("Pete Read", 27);
INSERT INTO users (name, age) VALUES ("Jacquie Roach", 26);
INSERT INTO users (name, age) VALUES ("Britt Maddox", 21);
INSERT INTO users (name, age) VALUES ("Aaron Harris", 32);
INSERT INTO users (name, age) VALUES ("Zack Morris", 18);
INSERT INTO users (name, age) VALUES ("A.C. Slater", 26);

INSERT INTO pledges (amount, user_id, project_id) VALUES (45, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 1, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 1, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (60, 2, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 2, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 3, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 3, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 4, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (60, 5, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 5, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 6, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 6, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 6, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 6, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 7, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 7, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 8, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 8, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (45, 9, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 10, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (30, 11, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 12, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 13, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 14, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 15, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 16, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 17, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 18, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 19, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 20, 1);
