INSERT INTO users (age) VALUES (20);
INSERT INTO users (age) VALUES (12);
INSERT INTO users (age) VALUES (24);
INSERT INTO users (age) VALUES (23);
INSERT INTO users (age) VALUES (22);
INSERT INTO users (age) VALUES (25);
INSERT INTO users (age) VALUES (29);
INSERT INTO users (age) VALUES (30);
INSERT INTO users (age) VALUES (31);
INSERT INTO users (age) VALUES (32);
INSERT INTO users (age) VALUES (33);
INSERT INTO users (age) VALUES (34);
INSERT INTO users (age) VALUES (35);
INSERT INTO users (age) VALUES (36);
INSERT INTO users (age) VALUES (37);
INSERT INTO users (age) VALUES (38);
INSERT INTO users (age) VALUES (39);
INSERT INTO users (age) VALUES (40);
INSERT INTO users (age) VALUES (41);
INSERT INTO users (age) VALUES (42);

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('A', 'fantasy', 100, 4/02/20, 4/02/21);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('X', 'entertainment', 200, 4/01/20, 4/01/21);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Z', 'housing', 300, 4/03/20, 4/03/21);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('B', 'sports', 400, 4/04/20, 4/04/21);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('C', 'literature', 500, 4/05/20, 4/05/21);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('D', 'SQL', 600, 4/06/20, 4/06/21);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('E', 'Ruby', 700, 4/07/20, 4/07/21);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('F', 'Business', 800, 4/08/20, 4/08/21);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('G', 'Education', 900, 4/09/20, 4/09/21);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('H', 'Government', 1000, 4/10/20, 4/10/21);

INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (11, 2, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (12, 3, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (13, 4, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (14, 5, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15, 6, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (16, 7, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (17, 8, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (18, 9, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 1);

     